name: deploy-to-payke.net

on:
  push:
    tags:
      - v**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: payke.net
    steps:
      - name: ssh
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
        run: |
          echo "$SECRET_KEY" > secret_key
          chmod 600 secret_key
          ssh -o StrictHostKeyChecking=no ${USER}@${HOST} -i secret_key  -p 10022 "cd /home/pke/payke.net/app_src/payke-ma && sh ./.github/workflows/deploy.sh"
