name: test-deploy-to-hirotae.xsrv.jp

on:
  push:
    tags:
      - test-**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
        run: |
          echo "$SECRET_KEY" > secret_key
          chmod 600 secret_key
          ssh -o StrictHostKeyChecking=no ${USER}@${HOST} -i secret_key "cd /home/hirotae/hirotae.xsrv.jp/app_resources/payke-ma && sh ./.github/workflows/deploy.sh"
